name: Integrated Chinese
favicon: null
layout_spectrum: 0.6936851146165282
typography_spectrum: 0.6254333320539445
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6254770327359438
  lightness: 0.4429217653814703
  saturation: 0.5943664007354528
  rhythmicContrast: 0.8701953052077442
purpose: []
